name: Build Ubuntu

on:
  pull_request:
    branches: [build]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: —Åheckout code
        uses: actions/checkout@v6
      - name: setup python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"
          cache-dependency-path: "**/requirements-build.txt"
      - run: pip install -r requirements-build.txt
      - name: build via pyinstaller
        run: sh build.sh
      - name: build via shiv
        run: sh build_shiv.sh
      - name: upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: wthr-linux
          path: dist/wthr
        uses: actions/upload-artifact@v6
        with:
          name: wthr-linux-pyz
          path: dist/wthr.pyz
